# 一,ndarray
## 1.ndarray的特性
### 多维性

In [ ]:
import numpy as np

In [3]:
arr=np.array(5) #创建了一个0维的ndarray数组
print(arr)
print('arr的维度:',arr.ndim)  #nummer of dimensions

5
arr的维度: 0


In [6]:
arr=np.array([1,2,3]) #创建了一个1维的ndarray数组
print(arr)
print('arr的维度:',arr.ndim)  #nummer of dimensions

[1 2 3]
arr的维度: 1


In [7]:
arr=np.array([[1,2,3],[4,5,6]]) #创建了一个2维的ndarray数组
print(arr)
print('arr的维度:',arr.ndim)  #nummer of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度: 2


### 同质性

In [ ]:
arr=np.array([1,'hello',3]) #不同的数据类型会被强制转换为相同的数据类型
print(arr)
print('arr的维度:',arr.ndim)  #nummer of dimensions

['1' 'hello' '3']
arr的维度: 1


In [ ]:
arr=np.array([1,2.5,3.7]) #不同的数据类型会被强制转换为相同的数据类型
print(arr)
print('arr的维度:',arr.ndim)  #nummer of dimensions
print(arr.shape)#数组形状
print(arr.size)#数组总元素个数
print(arr.dtype)#数组元素类型

[1.  2.5 3.7]
arr的维度: 1
(3,)
3
float64


## 2.nuarray的属性

In [23]:
arr=np.array(1)
print(arr)
print('数组的形状:',arr.shape)
print('数组的长度:',arr.size)
print('数组的维度:',arr.ndim)
print('数组的类型:',arr.dtype)
print('数组元素的转置:',arr.T)


1
数组的形状: ()
数组的长度: 1
数组的维度: 0
数组的类型: int32
数组元素的转置: 1


In [22]:
arr=np.array([1,2,3])
print(arr)
print('数组的形状:',arr.shape)
print('数组的长度:',arr.size)
print('数组的维度:',arr.ndim)
print('数组的类型:',arr.dtype)
print('数组元素的转置:',arr.T)

[1 2 3]
数组的形状: (3,)
数组的长度: 3
数组的维度: 1
数组的类型: int32
数组元素的转置: [1 2 3]


In [21]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状:',arr.shape)
print('数组的长度:',arr.size)
print('数组的维度:',arr.ndim)
print('数组的类型:',arr.dtype)
print('数组元素的转置:',arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状: (2, 3)
数组的长度: 6
数组的维度: 2
数组的类型: int32
数组元素的转置: [[1 4]
 [2 5]
 [3 6]]


## 3.nparray的创建

In [26]:
# 基础的创建方法
list1=[4,5,6]
arr=np.array(list1,dtype=np.float32)
print(arr)

[4. 5. 6.]


In [27]:
arr1=np.copy(arr)
print(arr1)

[4. 5. 6.]


In [32]:
print(arr is arr1)
print(id(arr),id(arr1) )

False
2717523810416 2717523619536


In [35]:
# 预定义形状
# 全0 全1 未初始化  固定值
# 全0
arr=np.zeros((2,3),dtype=int)
print(arr)
print(arr.dtype)
print(type(arr))

[[0 0 0]
 [0 0 0]]
int32
<class 'numpy.ndarray'>


In [41]:
# 全0 全1 未初始化  固定值
# 全0
arr=np.zeros((2,),dtype=int)
print(arr)
print(arr.dtype)
print(type(arr))

[0 0]
int32
<class 'numpy.ndarray'>


In [43]:
#全1
arr=np.ones((5,8),dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [77]:
# 未初始化
arr=np.empty((4,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [84]:
# 未初始化
arr=np.empty((5,3),dtype=int)
print(arr)

[[      0       0       0]
 [      0       0       0]
 [      0       0       0]
 [      0    1636       0]
 [      0 4980828       0]]


In [ ]:
# 给数组中指定元素值
arr=np.full((5,3),fill_value=2025)
print(arr)

[[2025 2025 2025]
 [2025 2025 2025]
 [2025 2025 2025]
 [2025 2025 2025]
 [2025 2025 2025]]


In [ ]:
# like 是模仿别的数组的形状，但是内容自己定义的语法
arr1=np.zeros_like(arr)
print(arr1)
arr1=np.empty_like(arr)
print(arr1)
arr1=np.ones_like(arr)
print(arr1)
arr1=np.full_like(arr,2026)
print(arr1)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]
 [2026 2026 2026]]


In [93]:
# 等差数列 2 4 6 8 10
arr=np.arange(1,10,1)  #start,end,step(步长)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [97]:
# 等差数列 2 4 6 8 10
arr=np.arange(2,11,2)  #start,end,step(步长)
print(arr)

[ 2  4  6  8 10]


In [101]:
#等间隔数列
app=np.linspace(0,100,5)
print(app)

[  0.  25.  50.  75. 100.]


In [104]:
#等间隔数列
app=np.linspace(0,100,5,dtype=int)
print(app)
app1=np.arange(0,101,25)
print(app1)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [107]:
# 对数间隔数列
arr=np.logspace(0,4,2,base=2)
print(arr)

[ 1. 16.]


In [113]:
# 特殊矩阵
# 单位矩阵:主对角线上(左上到↘右下)的数字为1,其他的数字为0
arr=np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [115]:
#   对角矩阵: 主对角线上非零的0,其他的为0
arr=np.diag([5,1,2,3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [122]:
#随机数的生成
#生成0-1之间的随机浮点数(均匀分布)
arr=np.random.rand(2,3)
print(arr)

[[0.69793964 0.49422391 0.63807589]
 [0.67615765 0.43974165 0.02292725]]


In [145]:
#生成指定范围的随机浮点数
arr=np.random.uniform(3,6,(2,3))
print(arr)

[[5.22926761 4.50542658 4.8881698 ]
 [4.31220584 3.05134813 4.19127998]]


In [161]:
#生成指定范围的随机整数
arr=np.random.randint(3,30,(2,3))
print(arr)

[[17 15  5]
 [13  7 23]]


In [174]:
# 生成随机数列(正态分布)
# 两边的概率比较小,中间的概率比较大，符合正态分布
arr=np.random.randn(2,3)
print(arr)

[[-0.70959534 -0.16577284  0.59265879]
 [-0.19711287 -0.58368955 -0.92933327]]


In [179]:
# 设置随机的种子
np.random.seed(20)
arr=np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4.ndarray的数据类型
## 布尔型：bool
## 整数类型：int uint
## 浮点型：float
## 复数：complex

In [185]:
arr=np.array([1,0,1,0,1,0],dtype=bool)
print(arr)

[ True False  True False  True False]


In [190]:
arr=np.array([1,0,127,0],dtype=int)
print(arr)

[  1   0 127   0]


In [209]:
# 5:索引和切片
#一维数组的索引和切片
arr=np.random.randint(1,100,20)
print(arr)
print(arr[0])
print(arr[:])
print(arr[5:10])
print(arr[5,])
print(arr[(arr>10) & (arr<50)]) #布尔索引
print(arr[slice(2,15,3)]) 

[65 88  6 44 79  1 23 83 26 89 73 93 58 43  9 62 16 67 51 96]
65
[65 88  6 44 79  1 23 83 26 89 73 93 58 43  9 62 16 67 51 96]
[ 1 23 83 26 89]
1
[44 23 26 43 16]
[ 6  1 26 93  9]


In [ ]:
# 二维数组的索引切片
arr=np.random.randint(1,100,(4,8))
print(arr)

[[59 67  9  1 23 39 82 68]
 [16 38  3 86 25 14 43 68]
 [97 15 51  1 18 42  8 80]
 [94 36 54 49 72 22 84 56]]
25


In [239]:
print(arr[1,4])
print(arr[1,:]) #第二行
print(arr[1,2:5]) #第一行第三四五列
print(arr[arr>50]) #查找大于50的元素

print(arr[2][ arr[2] >50] )#查找第三行大于50的元素
print(arr[:,3])
print(arr[:,3][arr[:,3]>10])#查找第列行大于20的元素

25
[16 38  3 86 25 14 43 68]
[ 3 86 25]
[59 67 82 68 86 68 97 51 80 94 54 72 84 56]
[97 51 80]
[ 1 86  1 49]
[86 49]


In [ ]:
# 5:ndarray的运算
#一维数组算数运算
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [248]:
c=[1,2,3]
d=[4,5,6]
for i in range(len(c)):
    d[i]=d[i]+c[i]
print(d)

[5, 7, 9]


In [ ]:
#二维数组算数运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]


In [250]:
#二维数组算数运算
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
# b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+3)
print(a-3)
print(a*3)
print(a/3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [ ]:
# 广播机制 ，
# 不同维度的数组进行计算的时候会进行广播机制，将数字的行和列填充满
# 1：先获取两个数组的形状
# 2：验证是否可以广播
# 3：进行计算
a=np.array([1,2,3])  #1*3
b=np.array([[4],[5],[6]])  #3*1
print(a)
print(b)
'''a
1 2 3
1 2 3
1 2 3
b
4 4 4
5 5 5
6 6 6
'''
print(a+b)


[1 2 3]
[[4]
 [5]
 [6]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#矩阵运算
f=np.array([[1,2,3],[4,5,6],[7,8,9]])
g=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(f@g)   #矩阵的乘法用@关键字
''' a
1 2 3
4 5 6
7 8 9
b
4 5 6 
7 8 9
1 2 3 
'''


[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


' a\n1 2 3\n4 5 6\n7 8 9\nb\n4 5 6 \n7 8 9\n1 2 3 \n'

# 2.3 numpy中的常用函数
## 1.基本的数学函数

In [259]:
#计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr=np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


In [ ]:
#计算指数 e^x=y
print(np.exp(1))  #e^1
print(np.exp(0))   #e^0

2.718281828459045
1.0


In [ ]:
#计算自然对数 lny=x
print(np.log(2.71))


0.9969486348916096


In [266]:
#计算三角函数值，正弦值，余弦值
print(np.sin(1))
print(np.sin(-1))
print(np.cos(np.pi))
print(np.sin(np.pi))


0.8414709848078965
-0.8414709848078965
-1.0
1.2246467991473532e-16


In [267]:
#计算绝对值
arr=np.array([-1,1,2,-3])
print(np.abs(arr))

[1 1 2 3]


In [271]:
#计算a的b次幂
arr=np.array([-1,1,2,-3])
print(np.power(arr,3))

[ -1   1   8 -27]


In [272]:
#四舍五入
print(np.round([3.2,4.5,8.6,9.2]))



[3. 4. 9. 9.]


In [274]:
#向上取证
arr=np.array([1.6,25.1,81.7])
print(np.ceil(arr)) #向上取整
print(np.floor(arr)) #向下取整

[ 2. 26. 82.]
[ 1. 25. 81.]


In [276]:
#检测缺失值NaN
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

In [279]:
# 2.统计函数
# 求和，计算平均值，计算中位数，标准差，方差，查找最大/最小值，计算分位差，累计和，累计差
arr=np.random.randint(1,20,8)
print(arr)


[11  1 12  2 10  2 11  8]


In [280]:
#求和
print(np.sum(arr))

57


In [ ]:
#计算平均值
print(np.average(arr))   #加权取平均值
print(np.mean(arr))    #求平均值

7.125
7.125


In [ ]:
#计算中位数、 奇数的话排序之后取中间值
#偶数的话，取排序后中间两个值的平均值
print(np.median([1,2,4,5,7,6,9,10,475]))
print(np.median([4,2,1]))
print(np.median([1,2,4,8]))

6.0
2.0
3.0


In [ ]:
#计算标准差和方差，标准差和方差是计算数据的离散程度
# 方差:每个数减去平均值的平方之和再除以总数
# 标准差:方差求根号
print(np.var([1,2,3]))  #方差  ((1-2)^2+(2-2)^2+(3-2)^2)/3=0.6666666666666666
print(np.std([1,2,3]))  #标准差  0.816496580927726

0.6666666666666666
0.816496580927726


In [ ]:
#计算最大值/最小值
print(np.min(arr),np.argmin(arr))  #求最小值和其索引位置
print(np.max(arr),np.argmax(arr))  #求最大值和其索引位置

1 1
12 2


In [293]:
#分位数
print(np.median([1,2,3]))
print(np.median([1,2,3,4]))
np.random.seed(0)
arr=np.random.randint(0,100,4)
print(arr)

2.0
2.5
[44 47 64 67]


In [ ]:
print(np.median(arr)) #中位数

55.5


In [295]:
print(np.percentile(arr,25))

46.25


In [ ]:
#累计和，累积积
arr=np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))  #第一项是是一个元素之和，第二个是前两个元素之和，第三个是前三个元素之和
print(np.cumprod(arr)) #第一项是是一个元素之积，第二个是前两个元素之积，第三个是前三个元素之积


6
[1 3 6]
[1 2 6]


## 比较函数
比较是否大于，小于，等于
逻辑与 或 非
检查数组中是否有一个True,是否所有的都为True,自定义去检查



In [306]:
#是否大于
print(np.greater([3,4,5,6,7],4))
#是否小于
print(np.less([3,4,5,6,7],4))
#是否等于
print(np.equal([3,4,5,6,7],4))
print(np.equal([3,4,5],[4,4,4]))  #数组比较是否一样

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False  True False]


In [308]:
#逻辑与或非
print(np.logical_and([1,0],[1,1]))
print(np.logical_or([0,0],[1,1]))
print(np.logical_not([1,0]))  #非是对一个元素进行计算

[ True False]
[ True  True]
[False  True]


In [311]:
#检查至少有一个元素为True
print(np.any([0,0,0,1]))
#检查是否全部元素为True
print(np.all([1,1,1,1,1]))

True
True


In [312]:
#自定义条件
# print(np.where(条件,符合条件,不符合条件))
arr=np.array([1,2,3,4,5])
print(np.where(arr>3,arr,0)) #查看数组中哪些元素大于3,大于3的返回，不大于3的用0填充

[0 0 0 4 5]


In [315]:
# 自定义条件
# print(np.where(条件,符合条件,不符合条件))
arr=np.array([1,2,3,4,5])
print(np.where(arr<3,1,0)) #查看数组中哪些元素小于3,小于3的返回1，不小于3的用0填充

[1 1 0 0 0]


In [333]:
score=np.random.randint(50,100,20)
print(score)

[51 80 87 92 50 69 56 79 53 81 79 66 53 76 56 91 87 61 67 93]


In [334]:
print(np.where(score>=60,'及格','不及格'))

['不及格' '及格' '及格' '及格' '不及格' '及格' '不及格' '及格' '不及格' '及格' '及格' '及格' '不及格'
 '及格' '不及格' '及格' '及格' '及格' '及格' '及格']


In [ ]:
print(np.where(   #嵌套
    score<60,'不及格',np.where(
        score<80,'良好','优秀'
        )
))

['不及格' '优秀' '优秀' '优秀' '不及格' '良好' '不及格' '良好' '不及格' '优秀' '良好' '良好' '不及格'
 '良好' '不及格' '优秀' '优秀' '良好' '良好' '优秀']


In [348]:
#np.select(条件,返回的结果)
print(np.select([score>80,(score<=80) & (score>=60) ,score<60],
                ['优秀','良好','不及格'],
                default='未知'))

['不及格' '良好' '优秀' '优秀' '不及格' '良好' '不及格' '良好' '不及格' '优秀' '良好' '良好' '不及格'
 '良好' '不及格' '优秀' '优秀' '良好' '良好' '优秀']


In [356]:
#排序函数
np.random.seed(0)
arr=np.random.randint(1,100,20)
print(arr)
print(arr.sort())
print(arr)
print(np.sort(arr))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
None
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]


In [357]:
#去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [361]:
#数组的拼接
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]


In [364]:
#数组的分割
print(np.split(arr,[6,12,18]))  #从6 12 18位置分割

[array([10, 13, 22, 37, 40, 45]), array([47, 48, 59, 65, 66, 68]), array([68, 71, 84, 88, 88, 89]), array([89, 89])]


In [367]:
#调整数组的形状
print(np.reshape(arr,[5,4]))

[[10 13 22 37]
 [40 45 47 48]
 [59 65 66 68]
 [68 71 84 88]
 [88 89 89 89]]


In [ ]:
# 练习题:某城市一周的天气温度是[28,30,29,31,32,30,29]
temps=np.array([28,30,29,31,32,30,29])
print('平均气温:','%.3f'%np.mean(temps))  #保留3为小数
print('最高气温:',np.max(temps))
print('最低气温:',np.min(temps))
print('气温超过30度的天数:',len(temps[temps>30]))   #第一种方法
print('气温超过30度的天数:',sum(np.where(temps>30,1,0)))   #第二种方法
print('气温超过30度的天数:',np.count_nonzero(temps>30))   #第三种方法,非零数据，列表中大于30就是1，一共是2条数据

平均气温: 29.857
最高气温: 32
最低气温: 28
气温超过30度的天数: 2
气温超过30度的天数: 2
气温超过30度的天数: 2


In [385]:
# 练习题:学生成绩统计
# 某班5名学生成绩为[85,90,78,92,88],计算成绩平均数,中位数，和方差,将成绩转换为百分制(10)
score1=np.array([85,90,78,92,88])
print(score1)
print('成绩平均数:',np.mean(score1))
print('成绩中位数:',np.median(score1))
print('成绩方差:',np.var(score1))
print('成绩标准差:','%.3f'%np.std(score1))
print(score1/10)

[85 90 78 92 88]
成绩平均数: 86.6
成绩中位数: 88.0
成绩方差: 23.84
成绩标准差: 4.883
[8.5 9.  7.8 9.2 8.8]


In [392]:
# 练习题:矩阵运算
# A=[[1,2],[3,4]]
# B=[[5,6],[7,8]]
# 计算A+B和A*B
# 计算A和B的矩阵乘法(点积)
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [ ]:
#随机数生成
# 生成一个(3,4)的随机整数数组,范围[0,10)
# 计算每列的最大值和每行的最小值
# 将数组中的所有奇数替换为-1
array=np.random.randint(0,10,(3,4))
print(array)

[[3 8 1 3]
 [3 3 7 0]
 [1 9 9 0]]


In [461]:
print('每列的最大值:',np.max(array,axis=0))   #axis=0代表列 axis=1代表行
print('每列的最大值的索引:',np.argmax(array,axis=0))
print('每行的最小值:',np.min(array,axis=1))
print('每行的最小值的索引:',np.argmin(array,axis=1))
array[array%2==1]=-1
print(array)
print(np.where(array%2==1,-1,array))

每列的最大值: [-1  8 -1  0]
每列的最大值的索引: [0 0 0 1]
每行的最小值: [-1 -1 -1]
每行的最小值的索引: [0 0 0]
[[-1  8 -1 -1]
 [-1 -1 -1  0]
 [-1 -1 -1  0]]
[[-1  8 -1 -1]
 [-1 -1 -1  0]
 [-1 -1 -1  0]]


In [479]:
# 练习5:数组变形
# 创建一个1到12的一维数组,并转换为(3,4)的二维数组
# 计算每行和每列的平均值
# 将数组展平为一维数组
# arry=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arry=np.arange(1,13)  #arange语法创建自然数的数组
print(arry)
arry3=arry.reshape(3,4) #并转换为(3,4)的二维数组
print('arry3数组是:',arry3)
print('每行的和:',arry3.sum(axis=1))  #每行的和
print('每列平均值:',arry3.mean(axis=0))  #每列平均值
print('每行平均值:',arry3.mean(axis=1))  #每行平均值
print('将数组展平为一个一维数组:',arry3.reshape(-1)) #将数组展平为一个一维数组 
print('将数组展平为一个一维数组:',arry3.ravel()) #将数组展平为一个一维数组 
print('将数组展平为一个一维数组:',np.reshape(arry3,12))



[ 1  2  3  4  5  6  7  8  9 10 11 12]
arry3数组是: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和: [10 26 42]
每列平均值: [5. 6. 7. 8.]
每行平均值: [ 2.5  6.5 10.5]
将数组展平为一个一维数组: [ 1  2  3  4  5  6  7  8  9 10 11 12]
将数组展平为一个一维数组: [ 1  2  3  4  5  6  7  8  9 10 11 12]
将数组展平为一个一维数组: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [457]:
'''
  0  1  2  3
0 1  2  3  4
1 5  6  7  8
2 9 10 11 12
'''
print('arry3数组是:',arry3)
print('第0行:',arry3[0]) #第0行
print('第1行:',arry3[1]) #第1行
print('第2行:',arry3[2]) #第2行
print('第0列:',arry3[:,0]) # 第0列
print('第1列:',arry3[:,1]) # 第1列
print('第2列:',arry3[:,2]) # 第2列
print('第3列:',arry3[:,3]) # 第3列
print('第0行 ~ 第1行:',arry3[0:2])
print('第0列 ~ 第2列:',arry3[:,0:2])

arry3数组是: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
第0行: [1 2 3 4]
第1行: [5 6 7 8]
第2行: [ 9 10 11 12]
第0列: [1 5 9]
第1列: [ 2  6 10]
第2列: [ 3  7 11]
第3列: [ 4  8 12]
第0行 ~ 第1行: [[1 2 3 4]
 [5 6 7 8]]
第0列 ~ 第2列: [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [503]:
# 创建一个(5,5)的随机数组,范围是[0-20)
# 找出数组中大于10的元素
# 将所有的大于10的元素替换为0
np.random.seed(0)
arr4=np.random.randint(0,20,(5,5))
print('arr4:',arr4)
print('数组中大于10的元素:',arr4[arr4>10])
print('所有的大于10的元素替换为0:',np.where(arr4>10,0,arr4))



arr4: [[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
数组中大于10的元素: [12 15 19 18 12 14 17 13 19 16 19]
所有的大于10的元素替换为0: [[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [518]:
# 练习7统计函数应用
# 某公司6个月的销售额为[120,135,110,125,130,140]
# 计算销售额的总和，均值和方差
# 找出销售最高的月份和最低的月份
sales=np.array([120,135,110,125,130,140])
print('销售额的总和:',np.sum(sales))
print('销售额的总和:',sales.sum())
print('销售额的均值:','%.3f'%np.mean(sales))
print('销售额的均值:','%.3f'%sales.mean())
print('销售额的方差:','%.3f'%np.var(sales))
print('销售额的方差:','%.3f'%sales.var())
print('销售额的标准差:','%.3f'%np.std(sales))
print('销售额的标准差:','%.3f'%sales.std())
print('销售额最高为:',np.max(sales),'月份为:',np.argmax(sales)+1)
print('销售额最高为:',sales.max(),'月份为:',sales.argmax()+1)
print('销售额最低为:',np.min(sales),'月份为:',np.argmin(sales)+1)
print('销售额最低为:',sales.min(),'月份为:',sales.argmin()+1)


销售额的总和: 760
销售额的总和: 760
销售额的均值: 126.667
销售额的均值: 126.667
销售额的方差: 97.222
销售额的方差: 97.222
销售额的标准差: 9.860
销售额的标准差: 9.860
销售额最高为: 140 月份为: 6
销售额最高为: 140 月份为: 6
销售额最低为: 110 月份为: 3
销售额最低为: 110 月份为: 3


In [530]:
#练习题：数组拼接
# A1=[1,2,3],B1=[4,5,6]
# 将A1和B1水平拼接为一个新数组
# 将A1和B1垂直拼接为一个新数组
A1=np.array([1,2,3])
B1=np.array([4,5,6])
print('水平拼接结果是:',np.hstack((A1,B1)))
print('水平拼接结果是:',np.concatenate((A1,B1)))
print('垂直拼接结果是:',np.vstack((A1,B1)))
print('垂直拼接结果是:',np.concatenate((A1,B1)).reshape(2,3))
print('垂直拼接结果是:',np.reshape(np.concatenate((A1,B1)),(2,3)))



水平拼接结果是: [1 2 3 4 5 6]
水平拼接结果是: [1 2 3 4 5 6]
垂直拼接结果是: [[1 2 3]
 [4 5 6]]
垂直拼接结果是: [[1 2 3]
 [4 5 6]]
垂直拼接结果是: [[1 2 3]
 [4 5 6]]


In [533]:
# 练习9唯一值与排序
# 给定数组[2,1,2,3,1,4,3]
# 找出数组中的唯一值并排序
# 计算每个唯一值出现的次数
arr5=np.array([2,1,2,3,1,4,3])
# 1. 获取【唯一值 + 排序】 + 【每个值出现次数】
unique_values,counts=np.unique(arr5,return_counts=True)
print("✅ 唯一值（已排序）：", unique_values)
print("✅ 对应出现次数：", counts)


✅ 唯一值（已排序）： [1 2 3 4]
✅ 对应出现次数： [2 2 2 1]


In [558]:
# 计算题：综合应用
# 某商店5天的销售额和成本如下
# 销售额:[20,25,22,30,28]
# 成本:  [15,18,16,22,20]
# 计算每天的利润
# 计算利润平均值和标准差
# 找出利润最高的是第几天
# 找出利润最高的有几天
sale=np.array([20,25,22,30,28])
cost=np.array([15,18,16,22,20])
profit=sale-cost
print('每天的利润:',profit)
print('利润的平均值',profit.mean())
print('利润的平均值',np.mean(profit))
print('利润的标准差',np.std(profit))
print('利润的标准差',profit.std())
print('利润最高为:',profit.max(),'是第：',profit.argmax()+1,'天')
s=(profit==profit.max()).sum()
print('利润最高的有:',s,'天')


每天的利润: [5 7 6 8 8]
利润的平均值 6.8
利润的平均值 6.8
利润的标准差 1.16619037896906
利润的标准差 1.16619037896906
利润最高为: 8 是第： 4 天
利润最高的有: 2 天
